# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ryan/StableMatching

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ryan/StableMatching

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ryan/StableMatching/CMakeFiles /home/ryan/StableMatching/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ryan/StableMatching/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GSAllocation

# Build rule for target.
GSAllocation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GSAllocation
.PHONY : GSAllocation

# fast build rule for target.
GSAllocation/fast:
	$(MAKE) -f CMakeFiles/GSAllocation.dir/build.make CMakeFiles/GSAllocation.dir/build
.PHONY : GSAllocation/fast

#=============================================================================
# Target rules for targets named GenerateDataFile

# Build rule for target.
GenerateDataFile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GenerateDataFile
.PHONY : GenerateDataFile

# fast build rule for target.
GenerateDataFile/fast:
	$(MAKE) -f CMakeFiles/GenerateDataFile.dir/build.make CMakeFiles/GenerateDataFile.dir/build
.PHONY : GenerateDataFile/fast

#=============================================================================
# Target rules for targets named HungarianAlgorithm

# Build rule for target.
HungarianAlgorithm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HungarianAlgorithm
.PHONY : HungarianAlgorithm

# fast build rule for target.
HungarianAlgorithm/fast:
	$(MAKE) -f CMakeFiles/HungarianAlgorithm.dir/build.make CMakeFiles/HungarianAlgorithm.dir/build
.PHONY : HungarianAlgorithm/fast

#=============================================================================
# Target rules for targets named RunTests

# Build rule for target.
RunTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RunTests
.PHONY : RunTests

# fast build rule for target.
RunTests/fast:
	$(MAKE) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/build
.PHONY : RunTests/fast

#=============================================================================
# Target rules for targets named StableMatching

# Build rule for target.
StableMatching: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StableMatching
.PHONY : StableMatching

# fast build rule for target.
StableMatching/fast:
	$(MAKE) -f CMakeFiles/StableMatching.dir/build.make CMakeFiles/StableMatching.dir/build
.PHONY : StableMatching/fast

GenerateDataFile.o: GenerateDataFile.cpp.o
.PHONY : GenerateDataFile.o

# target to build an object file
GenerateDataFile.cpp.o:
	$(MAKE) -f CMakeFiles/GenerateDataFile.dir/build.make CMakeFiles/GenerateDataFile.dir/GenerateDataFile.cpp.o
.PHONY : GenerateDataFile.cpp.o

GenerateDataFile.i: GenerateDataFile.cpp.i
.PHONY : GenerateDataFile.i

# target to preprocess a source file
GenerateDataFile.cpp.i:
	$(MAKE) -f CMakeFiles/GenerateDataFile.dir/build.make CMakeFiles/GenerateDataFile.dir/GenerateDataFile.cpp.i
.PHONY : GenerateDataFile.cpp.i

GenerateDataFile.s: GenerateDataFile.cpp.s
.PHONY : GenerateDataFile.s

# target to generate assembly for a file
GenerateDataFile.cpp.s:
	$(MAKE) -f CMakeFiles/GenerateDataFile.dir/build.make CMakeFiles/GenerateDataFile.dir/GenerateDataFile.cpp.s
.PHONY : GenerateDataFile.cpp.s

GreedyMatching.o: GreedyMatching.cpp.o
.PHONY : GreedyMatching.o

# target to build an object file
GreedyMatching.cpp.o:
	$(MAKE) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/GreedyMatching.cpp.o
.PHONY : GreedyMatching.cpp.o

GreedyMatching.i: GreedyMatching.cpp.i
.PHONY : GreedyMatching.i

# target to preprocess a source file
GreedyMatching.cpp.i:
	$(MAKE) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/GreedyMatching.cpp.i
.PHONY : GreedyMatching.cpp.i

GreedyMatching.s: GreedyMatching.cpp.s
.PHONY : GreedyMatching.s

# target to generate assembly for a file
GreedyMatching.cpp.s:
	$(MAKE) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/GreedyMatching.cpp.s
.PHONY : GreedyMatching.cpp.s

HungarianAlgorithm.o: HungarianAlgorithm.cpp.o
.PHONY : HungarianAlgorithm.o

# target to build an object file
HungarianAlgorithm.cpp.o:
	$(MAKE) -f CMakeFiles/HungarianAlgorithm.dir/build.make CMakeFiles/HungarianAlgorithm.dir/HungarianAlgorithm.cpp.o
	$(MAKE) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/HungarianAlgorithm.cpp.o
.PHONY : HungarianAlgorithm.cpp.o

HungarianAlgorithm.i: HungarianAlgorithm.cpp.i
.PHONY : HungarianAlgorithm.i

# target to preprocess a source file
HungarianAlgorithm.cpp.i:
	$(MAKE) -f CMakeFiles/HungarianAlgorithm.dir/build.make CMakeFiles/HungarianAlgorithm.dir/HungarianAlgorithm.cpp.i
	$(MAKE) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/HungarianAlgorithm.cpp.i
.PHONY : HungarianAlgorithm.cpp.i

HungarianAlgorithm.s: HungarianAlgorithm.cpp.s
.PHONY : HungarianAlgorithm.s

# target to generate assembly for a file
HungarianAlgorithm.cpp.s:
	$(MAKE) -f CMakeFiles/HungarianAlgorithm.dir/build.make CMakeFiles/HungarianAlgorithm.dir/HungarianAlgorithm.cpp.s
	$(MAKE) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/HungarianAlgorithm.cpp.s
.PHONY : HungarianAlgorithm.cpp.s

RunTests.o: RunTests.cpp.o
.PHONY : RunTests.o

# target to build an object file
RunTests.cpp.o:
	$(MAKE) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/RunTests.cpp.o
.PHONY : RunTests.cpp.o

RunTests.i: RunTests.cpp.i
.PHONY : RunTests.i

# target to preprocess a source file
RunTests.cpp.i:
	$(MAKE) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/RunTests.cpp.i
.PHONY : RunTests.cpp.i

RunTests.s: RunTests.cpp.s
.PHONY : RunTests.s

# target to generate assembly for a file
RunTests.cpp.s:
	$(MAKE) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/RunTests.cpp.s
.PHONY : RunTests.cpp.s

depreciated/GaleShapleyAllocation.o: depreciated/GaleShapleyAllocation.cpp.o
.PHONY : depreciated/GaleShapleyAllocation.o

# target to build an object file
depreciated/GaleShapleyAllocation.cpp.o:
	$(MAKE) -f CMakeFiles/GSAllocation.dir/build.make CMakeFiles/GSAllocation.dir/depreciated/GaleShapleyAllocation.cpp.o
.PHONY : depreciated/GaleShapleyAllocation.cpp.o

depreciated/GaleShapleyAllocation.i: depreciated/GaleShapleyAllocation.cpp.i
.PHONY : depreciated/GaleShapleyAllocation.i

# target to preprocess a source file
depreciated/GaleShapleyAllocation.cpp.i:
	$(MAKE) -f CMakeFiles/GSAllocation.dir/build.make CMakeFiles/GSAllocation.dir/depreciated/GaleShapleyAllocation.cpp.i
.PHONY : depreciated/GaleShapleyAllocation.cpp.i

depreciated/GaleShapleyAllocation.s: depreciated/GaleShapleyAllocation.cpp.s
.PHONY : depreciated/GaleShapleyAllocation.s

# target to generate assembly for a file
depreciated/GaleShapleyAllocation.cpp.s:
	$(MAKE) -f CMakeFiles/GSAllocation.dir/build.make CMakeFiles/GSAllocation.dir/depreciated/GaleShapleyAllocation.cpp.s
.PHONY : depreciated/GaleShapleyAllocation.cpp.s

depreciated/galeShapley.o: depreciated/galeShapley.cpp.o
.PHONY : depreciated/galeShapley.o

# target to build an object file
depreciated/galeShapley.cpp.o:
	$(MAKE) -f CMakeFiles/StableMatching.dir/build.make CMakeFiles/StableMatching.dir/depreciated/galeShapley.cpp.o
.PHONY : depreciated/galeShapley.cpp.o

depreciated/galeShapley.i: depreciated/galeShapley.cpp.i
.PHONY : depreciated/galeShapley.i

# target to preprocess a source file
depreciated/galeShapley.cpp.i:
	$(MAKE) -f CMakeFiles/StableMatching.dir/build.make CMakeFiles/StableMatching.dir/depreciated/galeShapley.cpp.i
.PHONY : depreciated/galeShapley.cpp.i

depreciated/galeShapley.s: depreciated/galeShapley.cpp.s
.PHONY : depreciated/galeShapley.s

# target to generate assembly for a file
depreciated/galeShapley.cpp.s:
	$(MAKE) -f CMakeFiles/StableMatching.dir/build.make CMakeFiles/StableMatching.dir/depreciated/galeShapley.cpp.s
.PHONY : depreciated/galeShapley.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... StableMatching"
	@echo "... edit_cache"
	@echo "... RunTests"
	@echo "... rebuild_cache"
	@echo "... GenerateDataFile"
	@echo "... HungarianAlgorithm"
	@echo "... GSAllocation"
	@echo "... GenerateDataFile.o"
	@echo "... GenerateDataFile.i"
	@echo "... GenerateDataFile.s"
	@echo "... GreedyMatching.o"
	@echo "... GreedyMatching.i"
	@echo "... GreedyMatching.s"
	@echo "... HungarianAlgorithm.o"
	@echo "... HungarianAlgorithm.i"
	@echo "... HungarianAlgorithm.s"
	@echo "... RunTests.o"
	@echo "... RunTests.i"
	@echo "... RunTests.s"
	@echo "... depreciated/GaleShapleyAllocation.o"
	@echo "... depreciated/GaleShapleyAllocation.i"
	@echo "... depreciated/GaleShapleyAllocation.s"
	@echo "... depreciated/galeShapley.o"
	@echo "... depreciated/galeShapley.i"
	@echo "... depreciated/galeShapley.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

